on:
  push:
    branches:
    - main
    - release/*
    

    
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: |
            ls
  hi-world:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "Hi, world!"
            echo "World Hi"
    needs: hello-world
      