on:
  push:
    branches:
    - main
    - release/*
  schedule:
  - cron: "*/2 7 * * *"

    
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            ls
  hi-world:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "Hi, world!"
            echo "World Hi"
    needs: hello-world
      